server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}] - %msg%n"