server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}] - %msg%n"

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key